const express=require("express"),http=require("http"),{Server}=require("socket.io"),{Pool}=require("pg"),multer=require("multer"),path=require("path"),fs=require("fs");
const app=express(),server=http.createServer(app),io=new Server(server);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("sslmode=require")?{rejectUnauthorized:false}:false});
const upload=multer({dest:"uploads/"});fs.mkdirSync("uploads",{recursive:true});
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static("public"));app.use("/uploads",express.static("uploads"));
const now=()=>new Date().toISOString();
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username TEXT UNIQUE,password TEXT,role TEXT,name TEXT);
CREATE TABLE IF NOT EXISTS trucks(id SERIAL PRIMARY KEY,truck_no TEXT UNIQUE,plate TEXT,driver TEXT,odometer DOUBLE PRECISION DEFAULT 0,lat DOUBLE PRECISION,lng DOUBLE PRECISION,status TEXT DEFAULT 'Offline',updated_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS trips(id SERIAL PRIMARY KEY,trip_no TEXT UNIQUE,truck_no TEXT,destination TEXT,lat DOUBLE PRECISION,lng DOUBLE PRECISION,radius DOUBLE PRECISION DEFAULT 200,status TEXT DEFAULT 'PENDING',start_time TIMESTAMPTZ,arrival_time TIMESTAMPTZ,departure_time TIMESTAMPTZ,arrival_lat DOUBLE PRECISION,arrival_lng DOUBLE PRECISION,departure_lat DOUBLE PRECISION,departure_lng DOUBLE PRECISION,photo TEXT);
CREATE TABLE IF NOT EXISTS gps_logs(id SERIAL PRIMARY KEY,truck_no TEXT,lat DOUBLE PRECISION,lng DOUBLE PRECISION,odometer DOUBLE PRECISION,speed DOUBLE PRECISION,created_at TIMESTAMPTZ)`);
await pool.query(`INSERT INTO users(username,password,role,name) VALUES('admin','1234','admin','Fleet Admin') ON CONFLICT(username) DO NOTHING`);
await pool.query(`INSERT INTO users(username,password,role,name) VALUES('driver','1234','driver','Demo Driver') ON CONFLICT(username) DO NOTHING`);
await pool.query(`INSERT INTO trucks(truck_no,plate,driver,odometer,status) VALUES('TRK-001','ABC-1234','Demo Driver',125430,'Offline') ON CONFLICT(truck_no) DO NOTHING`)}
const emit=()=>io.emit("fleet:update");
app.post("/api/login",async(req,res)=>{try{let r=await pool.query("SELECT id,username,role,name FROM users WHERE username=$1 AND password=$2",[req.body.username,req.body.password]);if(!r.rows[0])return res.status(401).json({error:"Invalid login"});res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/trucks",async(_,res)=>res.json((await pool.query("SELECT * FROM trucks ORDER BY truck_no")).rows));
app.get("/api/trips",async(_,res)=>res.json((await pool.query("SELECT * FROM trips ORDER BY id DESC")).rows));
app.post("/api/trucks",async(req,res)=>{try{let {truck_no,plate,driver,odometer}=req.body;await pool.query("INSERT INTO trucks(truck_no,plate,driver,odometer,status) VALUES($1,$2,$3,$4,'Offline')",[truck_no,plate,driver,odometer||0]);emit();res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/trips",async(req,res)=>{try{let {trip_no,truck_no,destination,lat,lng,radius}=req.body;await pool.query("INSERT INTO trips(trip_no,truck_no,destination,lat,lng,radius) VALUES($1,$2,$3,$4,$5,$6)",[trip_no,truck_no,destination,lat,lng,radius||200]);emit();res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
function dist(a,b,c,d){let R=6371000,r=x=>x*Math.PI/180,da=r(c-a),db=r(d-b),x=Math.sin(da/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
async function geofence(truck,lat,lng){let q=await pool.query("SELECT * FROM trips WHERE truck_no=$1 AND status IN ('EN ROUTE','ARRIVED') ORDER BY id DESC LIMIT 1",[truck]);let t=q.rows[0];if(!t)return;let inside=dist(lat,lng,t.lat,t.lng)<=t.radius;if(inside&&t.status==="EN ROUTE")await pool.query("UPDATE trips SET status='ARRIVED',arrival_time=$1,arrival_lat=$2,arrival_lng=$3 WHERE id=$4",[now(),lat,lng,t.id]);if(!inside&&t.status==="ARRIVED")await pool.query("UPDATE trips SET status='COMPLETED',departure_time=$1,departure_lat=$2,departure_lng=$3 WHERE id=$4",[now(),lat,lng,t.id])}

app.get("/api/drivers",async(_,res)=>{try{res.json((await pool.query("SELECT id,username,name,role FROM users WHERE role='driver' ORDER BY name")).rows)}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/drivers",async(req,res)=>{try{let {username,password,name}=req.body;await pool.query("INSERT INTO users(username,password,role,name) VALUES($1,$2,'driver',$3)",[username,password,name]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.put("/api/drivers/:id",async(req,res)=>{try{let {name,password}=req.body;await pool.query("UPDATE users SET name=COALESCE($1,name),password=COALESCE(NULLIF($2,''),password) WHERE id=$3 AND role='driver'",[name,password,req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete("/api/drivers/:id",async(req,res)=>{try{await pool.query("DELETE FROM users WHERE id=$1 AND role='driver'",[req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/gps",async(req,res)=>{try{let {truck_no,lat,lng,odometer,speed}=req.body;await pool.query("UPDATE trucks SET lat=$1,lng=$2,odometer=$3,status=$4,updated_at=$5 WHERE truck_no=$6",[lat,lng,odometer||0,(speed||0)>3?"Moving":"Stopped",now(),truck_no]);await pool.query("INSERT INTO gps_logs(truck_no,lat,lng,odometer,speed,created_at) VALUES($1,$2,$3,$4,$5,$6)",[truck_no,lat,lng,odometer||0,speed||0,now()]);await geofence(truck_no,lat,lng);emit();res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/trips/:id/start",async(req,res)=>{await pool.query("UPDATE trips SET status='EN ROUTE',start_time=$1 WHERE id=$2",[now(),req.params.id]);emit();res.json({ok:true})});
app.post("/api/trips/:id/depart",async(req,res)=>{let {lat,lng}=req.body;await pool.query("UPDATE trips SET status='COMPLETED',departure_time=$1,departure_lat=$2,departure_lng=$3 WHERE id=$4",[now(),lat,lng,req.params.id]);emit();res.json({ok:true})});
app.post("/api/trips/:id/photo",upload.single("photo"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"No photo"});let ext=path.extname(req.file.originalname)||".jpg",name=req.file.filename+ext;fs.renameSync(req.file.path,path.join("uploads",name));await pool.query("UPDATE trips SET photo=$1 WHERE id=$2",["/uploads/"+name,req.params.id]);emit();res.json({photo:"/uploads/"+name})});
app.get("/api/export",async(_,res)=>{let rows=(await pool.query("SELECT trip_no,truck_no,destination,status,start_time,arrival_time,departure_time,arrival_lat,arrival_lng,departure_lat,departure_lng,photo FROM trips ORDER BY id DESC")).rows;let h=Object.keys(rows[0]||{trip_no:""});let csv=[h.join(","),...rows.map(r=>h.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n");res.type("text/csv").attachment("fleet-trips.csv").send(csv)});
app.get("/health",(_,res)=>res.json({ok:true}));
io.on("connection",s=>s.emit("fleet:update"));
init().then(()=>server.listen(process.env.PORT||3000,()=>console.log("FleetTrack V3 online server ready"))).catch(e=>{console.error(e);process.exit(1)});
